version: '3.7'

networks:
  lab-network:

services:
  lab-mysql:
    image: mysql:8.0
    container_name: lab-mysql
    restart: always
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql
      - ./dockerfiles/mysql/init:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    networks:
      - lab-network

  lab-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lab-phpmyadmin
    depends_on:
      - lab-mysql
    env_file:
      - .env
    environment:
      - PMA_HOST=lab-mysql
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - $MYADMI_PUBLIC_PORT:80
    networks:
      - lab-network

  lab-backend:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    container_name: lab-backend
    restart: always
    volumes:
      - ./backend:/var/www/backend
    networks:
      - lab-network
    depends_on:
      - lab-mysql
    env_file:
      - .env
  lab-nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.root.dockerfile
    container_name: lab-nginx
    restart: always
    env_file:
      - .env
    ports:
      - $NGINX_PUBLIC_PORT:$NGINX_DOCKER_PORT
    volumes:
      - ./backend:/var/www/backend
    networks:
      - lab-network

  lab-get-review:
    build:
      context: ./backend/public/get_grade
      dockerfile: py_container.dockerfile
    container_name: lab-get-review
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/public/get_grade:/backend/public/get_grade
    networks:
      - lab-network

